import { type Key } from "./types";

// JSON generated by script/fetchPhysicalLayouts.ts
// DO NOT EDIT THIS FILE DIRECTLY
// Run `pnpm layouts path/to/zmk`
import data from "./physicalLayouts.json";

interface Layouts {
  [category: string]: {
    name: string;
    keys: Key[];
  }[]
}

export function getLayouts(): Layouts {
  const layouts: Layouts = {};
  for (const [category, compactLayouts] of Object.entries(data)) {
    layouts[category] = [];
    for (const compactLayout of compactLayouts) {
      const keys: Key[] = compactLayout.keys.map((key) => {
        const [row, col, w, h, x, y, r, rx, ry] = key;
        return {
          partOf: 0, // default to part 0
          row,
          column: col,
          width: w / 100,
          height: h / 100,
          x: x / 100,
          y: y / 100,
          r: r / 100,
          rx: rx / 100,
          ry: ry / 100,
        } satisfies Key;
      })
      layouts[category].push({
        name: compactLayout.name,
        keys,
      });
    }
  }
  return layouts;
}

export const layouts = getLayouts();
